version: '3.5'
services:
  seb-webservice:
      build:
          context: .
          dockerfile: ../sebserver.Dockerfile
          args:
            - GIT_TAG=development
            - SEBSERVER_VERSION=
      container_name: seb-webservice
      volumes:
        - seb-server-config:/sebserver/config
        - ./config/spring:/sebserver/config/spring
      environment:
        - SERVICE_PROFILE=ws
        - MONITORING_MODE=false
      # - JMX_PORT=9090 # Connect this port to host if you want to use JMX (MONITORING_MODE=true)
      ports:
        - 8081:8080
      # - 9090:9090 # Connect this port to host if you want to use JMX (MONITORING_MODE=true)
      networks:
        - seb-server-network
      restart: unless-stopped
      

volumes:
  seb-server-config:

networks:
  seb-server-network:
    name: seb-server-network