version: '3.5'
services:
  seb-guiservice:
      build:
          context: .
          dockerfile: sebguiservice.Dockerfile
          args:
            - GIT_TAG=development
            - SEBSERVER_VERSION=1.0.1
      container_name: seb-guiservice
      volumes:
        - seb-server-config:/sebserver/config
        - ./config/spring:/sebserver/config/spring
        - seb-server-logs:/sebserver/log
      environment:
        - SECRET=somePW
      ports:
        - 80:8080
      logging:
        driver: "json-file"
        options:
            mode: "non-blocking"
            max-size: "200k"
            max-file: "10"
      networks:
        - seb-server-network
      restart: unless-stopped

volumes:
  seb-server-config:
  seb-server-logs:
    name: seb-guiservice-logs

networks:
  seb-server-network:
    name: seb-server-network