apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: seb-server
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: sebserver.let.ethz.ch
    http:
      paths:
        - backend:
            serviceName: seb-server-gui
            servicePort: 8080
  tls:
    - hosts:
        - sebserver.let.ethz.ch
      secretName: auto-cert-sebserver
