version: '3'
services:
  mariadb: 
    image: "mariadb/server:10.3"
    container_name: seb-server-mariadb
    environment:
        MYSQL_ROOT_PASSWORD: somePW
    volumes:
        - seb-server-mariadb-data:/var/lib/mysql
    ports:
        - 3306:3306
    networks:
        - ralph

  seb-server:
      build:
          context: .
          args:
              - GIT_TAG=
              - SEBSERVER_VERSION=0.4.2-beta
      container_name: seb-server
      environment:
          - SERVER_PORT=8080
          - DBSERVER_PWD=somePW
          - GUICLIENT_PWD=somePW
          - INTERNAL_PWD=somePW
      volumes:
        - ./config:/sebserver/config

      ports:
          - 8080:8080
          - 9090:9090
      networks:
          - ralph
      depends_on:
          - "mariadb"
            
networks:
  ralph:
  
volumes:
  seb-server-mariadb-data: