namespace: seb-server-prod
nameSuffix: -prod

replicas:
  - name: seb-guiservice
    count: 1

images:
  - name: anhefti/seb-server
    newTag: v1.1-latest

resources:
  # Get the base configuration
  - https://github.com/SafeExamBrowser/seb-server-setup/docker/ethz/cloud/kustomize?ref=kustomize

  # Add an ingress
  - ingress.yml

  # Add a secret with application variables
  - app-env.json
  # - app-env.yml  # if prepared with SealedSecret as shown in the README

  # Same with DB connection variables
  - db-env.json

patchesStrategicMerge:
  # Add/replace some variables 
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: seb-webservice
    spec:
      template:
        spec:
          containers:
            - name: seb-webservice
              env:
                # NOTE: Set the below settings for database connection
                - name: "datastore_mariadb_server_address"
                  value: "seb-mariadb-prod.seb-server-prod.svc.cluster.local"
                - name: "datastore_mariadb_server_port"
                  value: "3306"
                - name: "spring_datasource_username"
                  value: "root"
                - name: "spring_datasource_password"
                  valueFrom:
                    secretKeyRef:
                      name: sebservermariadbpassword
                      key: DB_SA_PWD
                # NOTE: Set the below URL component settings from where the web-service is externally available
                - name: "sebserver_webservice_http_external_scheme"
                  value: "http"
                - name: "sebserver_webservice_http_external_servername"
                  value: "seb-webservice"
                - name: "sebserver_webservice_http_external_port"
                  value: ""
#              valueFrom:
#                secretKeyRef:
#                - name: sebservercredentials-prod
#                  key: SEBSERVER_PWD
#                    - name: DB_HOST
#                      valueFrom:
#                        secretKeyRef:
#                          name: sebservermariadbhost-prod
#                          key: DB_HOST
#                    - name: DB_USER
#                      valueFrom:
#                        secretKeyRef:
#                          name: sebservermariadbuser-prod
#                          key: DB_USER
#                - name: sebservermariadbpassword
#                  valueFrom:
#                    secretKeyRef:
#                      name: sebservermariadbpassword-prod
#                      key: DB_PASSWORD
#
