version: '3.5'
services:
  seb-guiservice:
      build:
          context: .
          dockerfile: ../sebserver.Dockerfile
          args:
            - GIT_TAG=development
            - SEBSERVER_VERSION=
      container_name: seb-guiservice
      volumes:
        - seb-server-config:/sebserver/config
        - ./config/spring:/sebserver/config/spring
        - ./config/jmx:/sebserver/config/jmx
      environment:
        - JAVA_HEAP_MIN=1G
        - JAVA_HEAP_MAX=8G
        - MONITORING_MODE=false
        - JMX_PORT=9090
        - spring_profiles_active=gui,prod-gui,prod
        - sebserver_password=${SEBSERVER_PWD}
        - sebserver_test_property=${SEBSERVER_SETUP_TAG}
        - sebserver_gui_http_external_servername=${SEBSERVER_EXT_HOST}
      ports:
        - 80:8080
      # - 9090:9090 # Connect this port to host if you want to use JMX (MONITORING_MODE=true)
      networks:
        - seb-server-network
      restart: unless-stopped

volumes:
  seb-server-config:

networks:
  seb-server-network:
    name: seb-server-network