---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seb-webservice
  labels:
    app: seb-webservice
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: seb-webservice
  replicas: 1
  template:
    metadata:
      labels:
        app: seb-webservice
    spec:
      volumes:
        - name: application-properties
          configMap:
            name: application-webservice-prod-properties
            items:
              - key: "application-prod.properties"
                path: "application-prod.properties"
              - key: "logback-prod.xml"
                path: "logback-prod.xml"
        - name: jmx-remote-access
          configMap:
            name: webservice-jmx-remote-access
            items:
              - key: "jmxremote.access"
                path: "jmxremote.access"
      containers:
        - name: seb-webservice
          image: anhefti/seb-server:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: application-properties
              mountPath: /sebserver/config/spring
            - name: jmx-remote-access
              mountPath: /sebserver/config/jmx
          env:
            - name: JAVA_HEAP_MIN
              value: "1G"
            - name: JAVA_HEAP_MAX
              value: "8G"
            - name: MONITORING_MODE
              value: "false"
            - name: JMX_PORT
              value: "9090"
            - name: "spring_profiles_active"
              value: "ws,prod-ws,prod"
              
# NOTE: Set the below settings for database connection
            - name: "datastore_mariadb_server_address"
              value: "seb-mariadb-prod.seb-server-prod.svc.cluster.local"
            - name: "datastore_mariadb_server_port"
              value: "3306"
            - name: "spring_datasource_username"
              value: "root"
            - name: "spring_datasource_password"
              valueFrom:
                secretKeyRef:
                  name: sebservermariadbpassword
                  key: DB_SA_PWD
                  
# NOTE: Set the below URL component settings from where the web-service is externally available
            - name: "sebserver_webservice_http_external_scheme"
              value: "http"
            - name: "sebserver_webservice_http_external_servername"
              value: "seb-webservice"
            - name: "sebserver_webservice_http_external_port"
              value: ""
              
            - name: "sebserver_password"
              valueFrom:
                secretKeyRef:
                  name: sebservercredentials
                  key: SEBSERVER_PWD
            
