---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seb-webservice
  labels:
    app: seb-webservice
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: seb-webservice
  replicas: 1
  template:
    metadata:
      labels:
        app: seb-webservice
    spec:
      volumes:
        - name: application-properties
          configMap:
            name: application-webservice-prod-properties
        - name: logback-xml
          configMap:
            name: logback-webservice-prod-xml
        - name: jmx-remote-access
          configMap:
            name: webservice-jmx-remote-access
      containers:
        - name: seb-webservice
          image: anhefti/seb-server:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: application-properties
              mountPath: /sebserver/config/spring/application-prod.properties
            - name: logback-xml
              mountPath: /sebserver/config/spring/logback-prod.xml
            - name: jmx-remote-access
              mountPath: /sebserver/config/jmx/jmxremote.access
          env:
            - name: JAVA_HEAP_MIN
              value: "1G"
            - name: JAVA_HEAP_MAX
              value: "8G"
            - name: MONITORING_MODE
              value: "false"
            - name: JMX_PORT
              value: "9090"
            - name: spring_profils_active
              value: "ws,prod-ws,prod"
              
# NOTE: Set the below settings for database connection
            - name: "datastore_mariadb_server_address"
              value: "seb-server-mariadb"
            - name: "datastore_mariadb_server_port"
              value: "3306"
            - name: "spring_datasource_username"
              value: "root"
            - name: sebservermariadbpassword
              valueFrom:
                secretKeyRef:
                  name: sebservermariadbpassword
                  key: DB_SA_PWD
                  
# NOTE: Set the below URL component settings from where the web-service is externally available
            - name: "sebserver_webservice_http_external_scheme"
              value: "http"
            - name: "sebserver_webservice_http_external_servername"
              value: "seb-webservice"
            - name: "sebserver_webservice_http_external_port"
              value: ""
              
            - name: sebserverpassword
              valueFrom:
                secretKeyRef:
                  name: sebservercredentials
                  key: SEBSERVER_PWD
            
