apiVersion: v1
kind: Service
metadata:
  name: seb-webservice
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
  selector:
    app: seb-webservice
