version: '3'
services:
  seb-server-setup:
    build:
        context: .
        dockerfile: setup.Dockerfile
    container_name: certificates
    volumes:
        - seb-server-config:/config
        - ./config:/host/config

  mariadb: 
    image: "mariadb/server:10.3"
    container_name: seb-server-mariadb
    environment:
        - MYSQL_ROOT_PASSWORD_FILE=/etc/mysql/conf.d/secret
    volumes:
        - seb-server-config:/etc/mysql/conf.d
        - seb-server-mariadb:/var/lib/mysql
    networks:
        - seb-server-network

  seb-server:
      build:
          context: .
          dockerfile: sebserver.Dockerfile
          args:
              - GIT_TAG=
              - SEBSERVER_JAR_VERSION=0.4.3-beta-SNAPSHOT
      container_name: seb-server
      volumes:
        - seb-server-config:/sebserver/config
        - ./config/spring:/sebserver/config/spring
      environment:
        - DEBUG_MODE=false
      logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "10"
      networks:
          - seb-server-network
      depends_on:
          - "mariadb"
          - "certificates"

  reverse-proxy:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - URL=yourdomain.url
      - SUBDOMAINS=www,
      - VALIDATION=http
      - EMAIL=e-mail #optional
      - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS=extradomains #optional
      - STAGING=true
    volumes:
      - ./config/nginx:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - seb-server-network
    depends_on:
      - "mariadb"
      - "seb-server"

networks:
  seb-server-network:

volumes:
  seb-server-config:
  seb-server-mariadb: