version: '3.5'
services:
  sebserver-ethz:
      build:
          context: .
          dockerfile: sebserver.Dockerfile
          args:
            - GIT_TAG=v1.1-latest
      container_name: sebserver-ethz
      volumes:
        - seb-server-config:/sebserver/config
        - ./config/spring:/sebserver/config/spring
        - ./config/jmx:/sebserver/config/jmx
      environment:
        - JAVA_HEAP_MIN=1G
        - JAVA_HEAP_MAX=8G
        - MONITORING_MODE=true
        - JMX_PORT=9090
        - spring_profiles_active=ws,gui,prod-ws,prod-gui,prod
        - sebserver_password=${SEBSERVER_PWD}
        - sebserver_mariadb_password=${DB_SA_PWD}
      ports:
        - 8080:8080
        - 9090:9090
      restart: unless-stopped
      
volumes:
  seb-server-config:
    name: seb-server-config

