version: '3.5'
services:
  seb-guiservice:
      image: anhefti/seb-server:docker-build-test
      container_name: seb-guiservice
      volumes:
        - seb-server-config:/sebserver/config
        - ./config/spring:/sebserver/config/spring
        - ./config/jmx:/sebserver/config/jmx
      environment:
        - JAVA_HEAP_MIN=1G
        - JAVA_HEAP_MAX=8G
        - MONITORING_MODE=false
        - JMX_PORT=9090
        - spring_profiles_active=gui,prod-gui,prod
        - sebserver_password=${SEBSERVER_PWD}
      ports:
        - 80:8080
      # - 9090:9090 # Connect this port to host if you want to use JMX (MONITORING_MODE=true)
      networks:
        - seb-server-network
      restart: unless-stopped

volumes:
  seb-server-config:

networks:
  seb-server-network:
    name: seb-server-network